### ISSUE TITLE
How to invoke chaincode as a particular user ?

### ISSUE THREAD

**Issue by malisetti** [worldsibu/convector-identity-patterns#2]
### Make the call again and successfully update the product
`hurl invoke identities product_update "prod1" "pineapples hello2modified" --user user1`

This example provides a way via `hurl` to invoke cc functions as a user. 

How to do the same using node sdk ?

**Comment by walmon** [comment]
Hi @mseshachalam you can see in the source code of Hurley how it does it behind the scenes: https://github.com/worldsibu/hurley/blob/develop/src/generators/invokechaincode.sh.ts#L30

That line I highlighted is a wrapper of `fabric-client` from the official Hyperledger SDK.

If you are using Convector it's the same as doing:
- https://github.com/instamed/healthcare-payments-blockchain/blob/master/packages/server/src/convectorUtils/convectorControllers.ts#L20

In case you didn't know about it we have a community where you can clear doubts similar to this faster: https://discord.gg/twRwpWt

Hope to see you around!

-- 
If you have further questions feel free to reopen the issue.
